auto login

diff --git a/create b/create
--- a/create
+++ b/create
@@ -17,6 +17,8 @@ export TF_IN_AUTOMATION="1"
 
 [ -d "$SCRIPTPATH/templates/$1" ] || fail "unknown template $1"
 
+$SCRIPTPATH/bin/get-token >/dev/null 2>/dev/null || terraform login || fail 'Error while login'
+
 echo "Deployment pending..."
 echo "1" | terraform init --backend=true -backend-config="organization=$2" "$SCRIPTPATH/templates/$1" >/dev/null
 
