destroy config

diff --git a/destroy b/destroy
--- a/destroy
+++ b/destroy
@@ -14,16 +14,16 @@ export TF_DATA_DIR="$SCRIPTPATH/.terraform"
 export TF_IN_AUTOMATION="1"
 [[ -z ${AUTO_APPROVE+x} ]] || export AUTO_APPROVE="-auto-approve"
 
-cd "$1" 2>/dev/null || fail "unknown template $1"
+[ -d "$SCRIPTPATH/templates/$1" ] || fail "unknown template $1"
 
 $SCRIPTPATH/bin/get-token >/dev/null 2>/dev/null || terraform login || fail 'Error while login'
 
-echo "1" | terraform init --backend=true -backend-config="organization=$2" >/dev/null
+echo "1" | terraform init --backend=true -backend-config="organization=$2" "$SCRIPTPATH/templates/$1" >/dev/null
 
-terraform workspace select "$3" || exit "1"
+terraform workspace select "$3" "$SCRIPTPATH/templates/$1" || exit "1"
 
 $SCRIPTPATH/bin/local-execution-mode "$2" "$1_$3" || exit "1"
 
-terraform destroy $AUTO_APPROVE || fail "destroy failed"
+terraform destroy $AUTO_APPROVE "$SCRIPTPATH/templates/$1" || fail "destroy failed"
 
 $SCRIPTPATH/bin/delete-tfc "$2" "$1_$3" || exit "1"
